### ISSUE TITLE
Set up Flask server

### ISSUE THREAD

**Issue by Budgetperson** [Budgetperson/IBDB#4]
For now, it just has to serve the static content.

**Comment by soolaymahn** [comment]
IP Address: 162.243.250.71
Root Password: teambooks123

**Comment by soolaymahn** [comment]
I followed this tutorial 

https://www.digitalocean.com/community/tutorials/how-to-deploy-a-flask-application-on-an-ubuntu-vps

**Comment by rohitspattanaik** [comment]
We get the default apache page when we go to litdb.me

**Comment by soolaymahn** [comment]
it should now go to the bootstrap page
